# Generated by Django 3.1.5 on 2021-02-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=10, verbose_name='全称')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级信息',
                'db_table': 'Class',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=10, verbose_name='全称')),
            ],
            options={
                'verbose_name': '院系',
                'verbose_name_plural': '院系信息',
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='ExamInfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=10, verbose_name='考试名称')),
                ('exam_date', models.DateField(verbose_name='考试时间')),
                ('exam_place', models.CharField(max_length=10, verbose_name='考试地点')),
                ('description', models.CharField(max_length=20, verbose_name='备注')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试信息查询',
                'db_table': 'ExamInfomation',
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=5, verbose_name='成员姓名')),
                ('member_age', models.IntegerField(verbose_name='成员年龄')),
                ('member_identity', models.CharField(max_length=5, verbose_name='与本人关系')),
                ('member_employer', models.CharField(max_length=20, verbose_name='成员工作单位')),
                ('description', models.CharField(max_length=20, verbose_name='备注')),
            ],
            options={
                'verbose_name': '信息',
                'verbose_name_plural': '家庭成员信息',
                'db_table': 'FamilyMember',
            },
        ),
        migrations.CreateModel(
            name='ScoreInquire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(verbose_name='序号')),
                ('semester', models.CharField(max_length=10, verbose_name='学期')),
                ('exam_subject', models.CharField(max_length=10, verbose_name='考试科目')),
                ('exam_categories', models.CharField(max_length=10, verbose_name='考试类别')),
                ('exam_time', models.DateField(verbose_name='考试时间')),
                ('exam_scores', models.FloatField(verbose_name='考试成绩')),
                ('description', models.CharField(max_length=20, verbose_name='备注')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩查询',
                'db_table': 'ScoreInquire',
            },
        ),
        migrations.CreateModel(
            name='TuitionInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=10, verbose_name='学期')),
                ('status', models.CharField(max_length=5, verbose_name='是否已缴费')),
                ('payment_method', models.CharField(choices=[('Alipay', '支付宝'), ('cash', '现金'), ('WeChat', '微信')], max_length=6, verbose_name='支付方式')),
                ('cost', models.IntegerField(verbose_name='费用')),
            ],
            options={
                'verbose_name': '学费',
                'verbose_name_plural': '学费管理',
                'db_table': 'TuitionInquiry',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='学号')),
                ('stu_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('stu_sex', models.CharField(choices=[('M', '男'), ('W', '女')], max_length=4, verbose_name='性别')),
                ('birth_date', models.CharField(max_length=10, verbose_name='出生日期')),
                ('identity_number', models.CharField(max_length=18, verbose_name='身份证号')),
                ('native_place', models.CharField(max_length=50, verbose_name='籍贯')),
                ('admission_time', models.CharField(max_length=10, verbose_name='入学时间')),
                ('home_address', models.CharField(max_length=50, verbose_name='家庭住址')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_manage.class', verbose_name='班级')),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_manage.department', verbose_name='院系')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生个人信息',
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='SchoolRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('YES', '变动'), ('NO', '无变动')], max_length=4, verbose_name='状态')),
                ('description', models.CharField(max_length=20, verbose_name='备注')),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_manage.student', verbose_name='学号')),
            ],
            options={
                'verbose_name': '学籍',
                'verbose_name_plural': '学籍变动',
                'db_table': 'SchoolRegister',
            },
        ),
        migrations.CreateModel(
            name='PunishInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punish_name', models.CharField(max_length=10, verbose_name='处分名称')),
                ('punish_date', models.DateField(verbose_name='处分时间')),
                ('degree', models.BooleanField(verbose_name='级别')),
                ('description', models.CharField(max_length=10, verbose_name='备注')),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_manage.student', verbose_name='学号')),
            ],
            options={
                'verbose_name': '处分',
                'verbose_name_plural': '处分信息',
                'db_table': 'PunishInformation',
            },
        ),
        migrations.CreateModel(
            name='AwardInformation',
            fields=[
                ('awaerd_name', models.CharField(max_length=20, verbose_name='奖项名称')),
                ('awaerd_date', models.DateField(verbose_name='获奖时间')),
                ('grade', models.BooleanField(primary_key=True, serialize=False, verbose_name='级别')),
                ('description', models.CharField(max_length=20, verbose_name='备注')),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_manage.student', verbose_name='学号')),
            ],
            options={
                'verbose_name': '获奖',
                'verbose_name_plural': '获奖信息',
                'db_table': 'AwardInformation',
            },
        ),
    ]
